#!/usr/bin/env python3
"""
Verify Firestore storage for Phase 4 testing.

This script queries Firestore to confirm:
1. Events were created in calendar_events collection
2. Strategy summary was saved to strategy_summaries collection
"""

import sys
import os

# Add parent directory to path
sys.path.insert(0, os.path.join(os.path.dirname(__file__), 'app'))

from google.cloud import firestore
from datetime import datetime
import json


def verify_events(db: firestore.Client, client_id: str, start_date: str, end_date: str):
    """Query calendar_events collection for the test data."""
    print("=" * 80)
    print("VERIFYING CALENDAR EVENTS")
    print("=" * 80)

    query = db.collection("calendar_events") \
        .where("client_id", "==", client_id) \
        .where("event_date", ">=", start_date) \
        .where("event_date", "<=", end_date)

    events = list(query.stream())

    print(f"\n✓ Found {len(events)} events for {client_id} ({start_date} to {end_date})\n")

    if events:
        print("Event Details:")
        for i, event_doc in enumerate(events, 1):
            event_data = event_doc.to_dict()
            print(f"\n  Event {i}:")
            print(f"    ID: {event_doc.id}")
            print(f"    Date: {event_data.get('event_date')}")
            print(f"    Title: {event_data.get('title')}")
            print(f"    Type: {event_data.get('event_type')}")
            print(f"    Send Time: {event_data.get('send_time')}")
            print(f"    Created: {event_data.get('created_at')}")
    else:
        print("  ⚠ No events found!")

    return len(events)


def verify_strategy_summary(db: firestore.Client, client_id: str):
    """Query strategy_summaries collection for the test data."""
    print("\n" + "=" * 80)
    print("VERIFYING STRATEGY SUMMARY")
    print("=" * 80)

    query = db.collection("strategy_summaries") \
        .where("client_id", "==", client_id) \
        .order_by("created_at", direction=firestore.Query.DESCENDING) \
        .limit(1)

    results = list(query.stream())

    if results:
        strategy_doc = results[0]
        strategy_data = strategy_doc.to_dict()

        print(f"\n✓ Found strategy summary for {client_id}\n")
        print(f"  Document ID: {strategy_doc.id}")
        print(f"  Date Range: {strategy_data.get('start_date')} to {strategy_data.get('end_date')}")
        print(f"  Generated By: {strategy_data.get('generated_by')}")
        print(f"  Event Count: {strategy_data.get('event_count')}")
        print(f"  Created At: {strategy_data.get('created_at')}")

        # Verify all 4 required fields
        required_fields = ['key_insights', 'targeting_approach', 'timing_strategy', 'content_strategy']
        print("\n  Required Fields Check:")

        all_fields_present = True
        for field in required_fields:
            if field in strategy_data:
                if field == 'key_insights':
                    count = len(strategy_data[field])
                    print(f"    ✓ {field}: {count} insights")
                else:
                    preview = strategy_data[field][:80] + "..." if len(strategy_data[field]) > 80 else strategy_data[field]
                    print(f"    ✓ {field}: {preview}")
            else:
                print(f"    ✗ {field}: MISSING")
                all_fields_present = False

        # Show key insights
        if 'key_insights' in strategy_data:
            print("\n  Key Insights:")
            for i, insight in enumerate(strategy_data['key_insights'], 1):
                print(f"    {i}. {insight[:100]}{'...' if len(insight) > 100 else ''}")

        return True, strategy_data
    else:
        print(f"\n✗ No strategy summary found for {client_id}")
        return False, None


def main():
    # Test parameters
    CLIENT_ID = "rogue-creamery"
    START_DATE = "2026-01-01"
    END_DATE = "2026-01-15"

    print("\n" + "=" * 80)
    print("PHASE 4 FIRESTORE VERIFICATION")
    print("=" * 80)
    print(f"Client: {CLIENT_ID}")
    print(f"Date Range: {START_DATE} to {END_DATE}")
    print(f"Timestamp: {datetime.now().isoformat()}")
    print()

    # Initialize Firestore
    db = firestore.Client()

    # Verify events
    event_count = verify_events(db, CLIENT_ID, START_DATE, END_DATE)

    # Verify strategy summary
    strategy_found, strategy_data = verify_strategy_summary(db, CLIENT_ID)

    # Summary
    print("\n" + "=" * 80)
    print("VERIFICATION SUMMARY")
    print("=" * 80)

    if event_count == 8:
        print("✓ Events: 8/8 found in Firestore")
    else:
        print(f"✗ Events: {event_count}/8 found (EXPECTED 8)")

    if strategy_found:
        print("✓ Strategy Summary: Found in Firestore")
        print("✓ All 4 required fields present")
    else:
        print("✗ Strategy Summary: NOT FOUND")

    print("\n" + "=" * 80)

    if event_count == 8 and strategy_found:
        print("✅ PHASE 4 TASK 3: PASSED - Data stored correctly in Firestore")
    else:
        print("❌ PHASE 4 TASK 3: FAILED - Data not fully persisted")

    print("=" * 80 + "\n")


if __name__ == "__main__":
    main()
