# Generated by tools/codegen.py
SCHEMA_HASH = 'e07d7a604517292f02046986f84431d0d1d51f8ccc03fc89990ba33bc8537db5'

from typing import Dict, Any
import importlib

REGISTRY = {
    'generate': 'agents.calendar_planner:create',
    'ingest': 'runtime.nodes_stubs:ingest',
    'publish': 'runtime.nodes_stubs:publish',
    'review': 'runtime.nodes_stubs:review',
    'validate': 'runtime.nodes_stubs:validate',
}

EDGES = [
    ('generate', 'validate', None),
    ('ingest', 'generate', None),
    ('review', 'publish', None),
    ('validate', 'generate', "not state.get('valid', False)"),
    ('validate', 'review', "state.get('valid', False)"),
]

def _resolve(dotted: str):
    mod, fn = dotted.split(':', 1)
    m = importlib.import_module(mod)
    return getattr(m, fn)

def run(state: Dict[str, Any]) -> Dict[str, Any]:
    current = state.get('start', REGISTRY and sorted(REGISTRY.keys())[0])
    visited = []
    while current:
        visited.append(current)
        fn = _resolve(REGISTRY[current])
        state = fn(state)
        # pick next edge by first matching condition or first edge
        nxt = None
        for fr,to,cond in EDGES:
            if fr != current: continue
            if cond is None: nxt = to; break
            try:
                # Expose state dict as name 'state' only
                if eval(cond, {'__builtins__':{}}, {'state': state}):
                    nxt = to; break
            except Exception:
                continue
        current = nxt
    state['visited'] = visited
    return state
