"""
Pydantic schemas for calendar operations
"""

from pydantic import BaseModel, Field
from datetime import datetime, date
from typing import Optional, List, Dict, Any

class CalendarEventBase(BaseModel):
    title: str = Field(..., min_length=1, max_length=255)
    content: Optional[str] = None
    event_date: date
    color: str = Field(default="bg-gray-200 text-gray-800", max_length=50)
    event_type: Optional[str] = None
    
    # Campaign details
    segment: Optional[str] = None
    send_time: Optional[str] = None
    subject_a: Optional[str] = None
    subject_b: Optional[str] = None
    preview_text: Optional[str] = None
    main_cta: Optional[str] = None
    offer: Optional[str] = None
    ab_test: Optional[str] = None

class CalendarEventCreate(CalendarEventBase):
    client_id: str

class CalendarEventUpdate(CalendarEventBase):
    title: Optional[str] = None
    event_date: Optional[date] = None
    client_id: Optional[str] = None

class CalendarEventResponse(CalendarEventBase):
    id: str
    client_id: str
    imported_from_doc: bool = False
    import_doc_id: Optional[str] = None
    original_event_id: Optional[str] = None
    created_at: datetime
    updated_at: datetime
    
    class Config:
        from_attributes = True

class GoogleDocImportRequest(BaseModel):
    client_id: str
    doc_id: str
    access_token: str

class CalendarChatRequest(BaseModel):
    client_id: str
    message: str
    chat_history: Optional[List[Dict[str, Any]]] = []

class AICalendarRequest(BaseModel):
    """Enhanced AI request for calendar operations"""
    message: str
    client_id: str
    chat_history: Optional[List[Dict[str, Any]]] = []
    context: Optional[Dict[str, Any]] = {}

class CampaignPlanRequest(BaseModel):
    """Request schema for AI-powered campaign planning"""
    client_id: str = Field(..., description="Client identifier")
    campaign_type: str = Field(..., description="Type of campaign: New Product, Limited Time Offer, Flash Sale, Other")
    start_date: str = Field(..., description="Campaign start date in YYYY-MM-DD format")
    end_date: str = Field(..., description="Campaign end date in YYYY-MM-DD format")
    promotion_details: str = Field(..., description="Details about the promotion, product, or campaign objective")

class CampaignPlanResponse(BaseModel):
    """Response schema for campaign planning"""
    campaign_plan: str = Field(..., description="AI-generated campaign strategy")
    events_created: List[Dict[str, Any]] = Field(..., description="List of calendar events created")
    total_events: int = Field(..., description="Total number of events created")
    touchpoints: Dict[str, int] = Field(..., description="Breakdown of touchpoints by type")

class AIAction(BaseModel):
    action: str  # create, update, delete
    event_id: Optional[str] = None
    event: Optional[Dict[str, Any]] = None
    updates: Optional[Dict[str, Any]] = None

class AIResponse(BaseModel):
    message: str
    is_action: bool = False
    action: Optional[AIAction] = None

class CalendarImportLogResponse(BaseModel):
    id: str
    client_id: str
    import_type: str
    source_id: Optional[str] = None
    status: str
    events_imported: int = 0
    events_updated: int = 0
    events_failed: int = 0
    error_message: Optional[str] = None
    started_at: datetime
    completed_at: Optional[datetime] = None
    
    class Config:
        from_attributes = True

class CalendarStatsResponse(BaseModel):
    total_events: int
    events_this_month: int
    events_next_month: int
    event_types: Dict[str, int]
    upcoming_events: List[CalendarEventResponse]

class CalendarExportResponse(BaseModel):
    client_name: str
    export_date: str
    total_events: int
    events: List[CalendarEventResponse]

# ============================================================================
# STRATEGY SUMMARY SCHEMAS (Phase 2: Backend Integration)
# ============================================================================

class StrategySummary(BaseModel):
    """
    AI-generated strategy summary for a calendar period.

    This model captures high-level marketing strategy generated by Claude Sonnet 4.5
    during calendar creation, providing strategic context for campaign planning.
    """
    key_insights: List[str] = Field(
        ...,
        min_length=1,
        max_length=10,
        description="3-5 strategic recommendations or key insights"
    )
    targeting_approach: str = Field(
        ...,
        min_length=10,
        max_length=2000,
        description="Audience segmentation and targeting strategy"
    )
    timing_strategy: str = Field(
        ...,
        min_length=10,
        max_length=2000,
        description="Send time optimization and timing recommendations"
    )
    content_strategy: str = Field(
        ...,
        min_length=10,
        max_length=2000,
        description="Content themes, messaging direction, and creative approach"
    )

    class Config:
        json_schema_extra = {
            "example": {
                "key_insights": [
                    "Focus on weekend warriors and outdoor enthusiasts",
                    "Leverage seasonal transitions for product launches",
                    "Build anticipation with multi-touch pre-launch sequence"
                ],
                "targeting_approach": "Segment by purchase history and engagement level. Create VIP tier for top 20% customers with exclusive early access.",
                "timing_strategy": "Send promotional emails Tuesday-Thursday 10 AM local time. Weekend content emails Saturday 8 AM for planning mindset.",
                "content_strategy": "Emphasize adventure and lifestyle benefits over product features. Use customer testimonials and UGC to build social proof."
            }
        }

class BulkEventsCreate(BaseModel):
    """
    Request schema for bulk calendar event creation with optional strategy summary.

    This schema supports importing multiple events in a single API call, with an
    optional AI-generated strategy summary that provides marketing context.
    """
    client_id: str = Field(..., description="Client identifier")
    events: List[CalendarEventCreate] = Field(
        ...,
        min_length=1,
        description="List of calendar events to create"
    )
    strategy_summary: Optional[StrategySummary] = Field(
        None,
        description="Optional AI-generated strategy summary for this calendar period"
    )

    class Config:
        json_schema_extra = {
            "example": {
                "client_id": "rogue-creamery",
                "events": [
                    {
                        "client_id": "rogue-creamery",
                        "title": "New Product Launch Email",
                        "event_date": "2026-01-15",
                        "content": "Introduce new artisan cheese line",
                        "event_type": "email",
                        "segment": "VIP Customers"
                    }
                ],
                "strategy_summary": {
                    "key_insights": ["Focus on quality and craftsmanship", "Emphasize local sourcing"],
                    "targeting_approach": "Target food enthusiasts and existing customers",
                    "timing_strategy": "Send during lunch hours for higher engagement",
                    "content_strategy": "Use storytelling to highlight artisan process"
                }
            }
        }

class BulkEventsResponse(BaseModel):
    """Response schema for bulk event creation"""
    success: bool
    events_created: int
    strategy_summary_saved: bool = False
    event_ids: List[str] = Field(default_factory=list, description="IDs of created events")
    sample_events: List[CalendarEventResponse] = Field(
        default_factory=list,
        max_length=5,
        description="Up to 5 sample events created"
    )
    message: Optional[str] = None

class StrategySummaryResponse(BaseModel):
    """Response schema for strategy summary retrieval"""
    client_id: str
    start_date: date
    end_date: date
    key_insights: List[str]
    targeting_approach: str
    timing_strategy: str
    content_strategy: str
    created_at: datetime
    updated_at: datetime
    generated_by: str = Field(default="claude-sonnet-4-5-20250929")
    event_count: int = Field(default=0, description="Number of events in this calendar period")

    class Config:
        from_attributes = True