"""
Node stubs - placeholder implementations for missing nodes
Generated by tools/codegen.py
"""

import logging

logger = logging.getLogger(__name__)


def ingest_stub(state):
    """Stub implementation for ingest"""
    import logging
    logging.warning(f"STUB: ingest - no implementation found")
    # Pass through state unchanged
    return state
def generate_stub(state):
    """Stub implementation for generate"""
    import logging
    logging.warning(f"STUB: generate - no implementation found")
    # Pass through state unchanged
    return state
def validate_stub(state):
    """Stub implementation for validate"""
    import logging
    logging.warning(f"STUB: validate - no implementation found")
    # Pass through state unchanged
    return state
def review_stub(state):
    """Stub implementation for review"""
    import logging
    logging.warning(f"STUB: review - no implementation found")
    # Pass through state unchanged
    return state
def publish_stub(state):
    """Stub implementation for publish"""
    import logging
    logging.warning(f"STUB: publish - no implementation found")
    # Pass through state unchanged
    return state
