# Google Cloud Build configuration for Email/SMS MCP Server
steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build', 
      '-t', 'gcr.io/$PROJECT_ID/email-sms-mcp-server:latest',
      '.'
    ]
  
  # Push the image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push', 
      'gcr.io/$PROJECT_ID/email-sms-mcp-server:latest'
    ]
  
  # Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'run', 'deploy', 'email-sms-mcp-server',
      '--image', 'gcr.io/$PROJECT_ID/email-sms-mcp-server:latest',
      '--platform', 'managed',
      '--region', 'us-central1',
      '--allow-unauthenticated',
      '--memory', '1Gi',
      '--cpu', '1',
      '--concurrency', '1000',
      '--timeout', '300',
      '--port', '8080',
      '--set-env-vars', 'ENVIRONMENT=production'
    ]

images:
  - 'gcr.io/$PROJECT_ID/email-sms-mcp-server:latest'

options:
  logging: CLOUD_LOGGING_ONLY