"""
Interactive calendar management assistant
Auto-generated by Agent Creator API
"""

from typing import Dict, Any
from ..agents.agent_v2 import Agent

class AbTestCoordinatorAgent(Agent):
    """
    Interactive calendar management assistant
    """
    
    def __init__(self):
        super().__init__(
            name="ab_test_coordinator",
            description="""Interactive calendar management assistant""",
            system_prompt="""You are a data expert great at pulling data an ensuring it is perfect for making decisions off of.

1. Pull {selected_month_2y_ago} and {selected_month_1y_ago} campaign data:
Campaign Title
Sends
Successful deliveries
{email_open_rate}
{email_click_rate}
{email_conversion_rate}
{email_bounce_rate}
{email_unsubscribe_rate}
{email_spam_rate}
{email_revenue_per_recipient}
{sms_click_rate}
{sms_conversion_rate}
{sms_opt_out_rate}
{sms_revenue_per_recipient}
{total_revenue}
{revenue_growth_rate}
{revenue_per_customer}
{average_order_value}
Click %
Placed-order %
Revenue
Revenue-per-recipient
Average-order-value
Unsubscribe / spam %
Send date & exact send time
Send-time-optimization score (if available)

2. Pull segment performance for "30 Day Engaged", {client_affinity_segment_1_name}, {client_affinity_segment_2_name}, {client_affinity_segment_3_name}
These are important because these are for: {client_affinity_segment_1_definition},{client_affinity_segment_2_definition},{client_affinity_segment_3_definition}
Pull any data you can on Mobile vs Desktop split and time zone distribution (flag if >15 % in any one time zone)
Inventory & launch data for SKUs with ≥ 10 units forecasted for {selected_month}, plus any limited-time products (do not hallucinate, pull from the data).

3. Make an ecommerce optimized calendar plan:
Topic
Rule
Calendar scope
Create 20 email and 4 SMS campaign ideas for {selected_month}.
Send-caps
Standard: max 2 total emails per account per week. Exception: subscribers tagged unengaged or churn-risk may receive 2 + promotional sends over the course of a month to drive re-engagement.
List health
Include at least one send to the entire mailable list; monitor % unengaged and flag deliverability risks.
Promos vs nurture
Only one multi-day promo (see “Key Dates”); all other sends are nurture/education with no discount.
Sales target
Hit ${goal_revenue} Klaviyo-attributed revenue (if none provided, aim for $80,000). Revenue mix:  70 % · Cheddars 15 % · Gift Sets 15 %.
Affinity groups
Every send must clearly map to one (or more) of: {client_affinity_segment_1_name},{client_affinity_segment_2_name},{client_affinity_segment_3_name}
{client_key_growth_objective} is the client's most important objective
Include dedicated Cheese-Club growth flows/campaigns.""",
            tools=['klaviyo', 'firestore'],
            max_iterations=10
        )
    
    async def run(self, task: str, **kwargs) -> Dict[str, Any]:
        """Execute the agent task"""
        return await self.execute(task, **kwargs)


# Export agent instance
ab_test_coordinator_agent = AbTestCoordinatorAgent()
