"""
A simple greeting agent for testing
Auto-generated by Agent Creator API
"""

from typing import Dict, Any
from ..agents.agent_v2 import Agent

class HelloWorldAgent(Agent):
    """
    A simple greeting agent for testing
    """
    
    def __init__(self):
        super().__init__(
            name="hello_world",
            description="""A simple greeting agent for testing""",
            system_prompt="""You are a friendly assistant. When someone says hello, respond with a warm greeting and ask how you can help them today. Keep responses brief and helpful.""",
            tools=[],
            max_iterations=5
        )
    
    async def run(self, task: str, **kwargs) -> Dict[str, Any]:
        """Execute the agent task"""
        return await self.execute(task, **kwargs)


# Export agent instance
hello_world_agent = HelloWorldAgent()
