"""
Simple agent without complex variable substitution
Auto-generated by Agent Creator API
"""

from typing import Dict, Any
from ..agents.agent_v2 import Agent

class SimpleAgentAgent(Agent):
    """
    Simple agent without complex variable substitution
    """
    
    def __init__(self):
        super().__init__(
            name="simple_agent",
            description="""Simple agent without complex variable substitution""",
            system_prompt="""You are a helpful AI assistant. Respond to user queries in a friendly and helpful manner.""",
            tools=[],
            max_iterations=3
        )
    
    async def run(self, task: str, **kwargs) -> Dict[str, Any]:
        """Execute the agent task"""
        return await self.execute(task, **kwargs)


# Export agent instance
simple_agent_agent = SimpleAgentAgent()
