"""
A test helper agent that provides friendly assistance
Auto-generated by Agent Creator API
"""

from typing import Dict, Any
from ..agents.agent_v2 import Agent

class TestHelperAgent(Agent):
    """
    A test helper agent that provides friendly assistance
    """
    
    def __init__(self):
        super().__init__(
            name="test_helper",
            description="""A test helper agent that provides friendly assistance""",
            system_prompt="""You are a helpful assistant. Task: {task}. Context: {context}. Provide a clear, friendly response that directly addresses the user request.""",
            tools=[],
            max_iterations=5
        )
    
    async def run(self, task: str, **kwargs) -> Dict[str, Any]:
        """Execute the agent task"""
        return await self.execute(task, **kwargs)


# Export agent instance
test_helper_agent = TestHelperAgent()
