"""
Agent that uses multiple system variables
Auto-generated by Agent Creator API
"""

from typing import Dict, Any
from ..agents.agent_v2 import Agent

class VariableTestAgentAgent(Agent):
    """
    Agent that uses multiple system variables
    """
    
    def __init__(self):
        super().__init__(
            name="variable_test_agent",
            description="""Agent that uses multiple system variables""",
            system_prompt="""You are a variable integration test agent. Current client: {client_name}, Date: {current_date}, Revenue: {total_revenue}, Open rate: {email_open_rate}""",
            tools=[],
            max_iterations=10
        )
    
    async def run(self, task: str, **kwargs) -> Dict[str, Any]:
        """Execute the agent task"""
        return await self.execute(task, **kwargs)


# Export agent instance
variable_test_agent_agent = VariableTestAgentAgent()
