"""
A working test agent with proper configuration
Auto-generated by Agent Creator API
"""

from typing import Dict, Any
from ..agents.agent_v2 import Agent

class WorkingTestAgentAgent(Agent):
    """
    A working test agent with proper configuration
    """
    
    def __init__(self):
        super().__init__(
            name="working_test_agent",
            description="""A working test agent with proper configuration""",
            system_prompt="""You are a helpful assistant. Respond directly to user queries without using any tools. Keep responses short and friendly.""",
            tools=[],
            max_iterations=0
        )
    
    async def run(self, task: str, **kwargs) -> Dict[str, Any]:
        """Execute the agent task"""
        return await self.execute(task, **kwargs)


# Export agent instance
working_test_agent_agent = WorkingTestAgentAgent()
