#!/bin/bash

# MCP Management System - Emergency Rollback Script
# Use this script to remove MCP Management from the browser if there are issues

set -e

echo "🔄 MCP Management System - Emergency Rollback"
echo "=============================================="

LOG_FILE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/rollback.log"

log() {
    echo "$(date '+%Y-%m-%d %H:%M:%S') - $1" | tee -a "$LOG_FILE"
}

log "Starting MCP Management rollback process..."

echo ""
echo "This script will help you remove MCP Management if there are issues."
echo ""
echo "ROLLBACK OPTIONS:"
echo "================="
echo ""
echo "1. Browser Console Rollback (Recommended)"
echo "   - Opens browser console commands to remove MCP"
echo "   - Safe and immediate"
echo ""
echo "2. Generate Cleanup Script"
echo "   - Creates a cleanup script to paste in console"
echo "   - Good for sharing with others"
echo ""
echo "3. Show Manual Instructions"
echo "   - Step-by-step removal instructions"
echo "   - For troubleshooting specific issues"
echo ""

read -p "Choose option (1-3): " choice

case $choice in
    1)
        echo ""
        echo "🔧 BROWSER CONSOLE ROLLBACK"
        echo "=========================="
        echo ""
        echo "1. Navigate to https://emailpilot.ai in your browser"
        echo "2. Open Developer Console (F12 or Cmd+Option+I)"
        echo "3. Copy and paste this code:"
        echo ""
        echo "// === MCP Management Removal Script ==="
        
        cat << 'EOF'
(function() {
    console.log('🗑️ Removing MCP Management System...');
    
    // Remove MCP button and modal
    const mcpRoot = document.getElementById('mcp-root');
    if (mcpRoot) {
        mcpRoot.remove();
        console.log('✅ Removed MCP root element');
    }
    
    // Remove MCP button by class
    const mcpButtons = document.querySelectorAll('[id*="mcp"], [class*="mcp"]');
    mcpButtons.forEach(button => {
        button.remove();
        console.log('✅ Removed MCP element:', button);
    });
    
    // Clear global variables
    delete window.MCPManagement;
    delete window.MCP_ENDPOINTS;
    delete window.MCP_CONFIG;
    console.log('✅ Cleared MCP global variables');
    
    // Remove any injected scripts
    const scripts = document.querySelectorAll('script');
    scripts.forEach(script => {
        if (script.innerHTML && script.innerHTML.includes('MCP') && script.innerHTML.includes('Management')) {
            script.remove();
            console.log('✅ Removed MCP script');
        }
    });
    
    console.log('🎉 MCP Management System completely removed!');
    console.log('🔄 Refresh the page to ensure clean state');
})();
EOF

        echo ""
        echo "4. Press Enter to execute"
        echo "5. Refresh the page"
        echo ""
        log "Provided browser console rollback instructions"
        ;;
        
    2)
        CLEANUP_SCRIPT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/mcp-cleanup.js"
        
        echo ""
        echo "📝 Generating cleanup script..."
        
        cat > "$CLEANUP_SCRIPT" << 'EOF'
// MCP Management System - Cleanup Script
// Generated by rollback.sh - Paste this in browser console

(function() {
    console.log('🧹 MCP Management Cleanup Starting...');
    
    let removedCount = 0;
    
    // Remove all MCP-related DOM elements
    const selectors = [
        '#mcp-root',
        '[id*="mcp"]',
        '[class*="mcp"]',
        '.mcp-overlay',
        '.mcp-modal',
        '[id="mcp-toggle-button"]'
    ];
    
    selectors.forEach(selector => {
        const elements = document.querySelectorAll(selector);
        elements.forEach(element => {
            element.remove();
            removedCount++;
            console.log(`✅ Removed element: ${selector}`);
        });
    });
    
    // Clean up global variables
    const mcpGlobals = ['MCPManagement', 'MCP_ENDPOINTS', 'MCP_CONFIG'];
    mcpGlobals.forEach(global => {
        if (window[global]) {
            delete window[global];
            console.log(`✅ Removed global: ${global}`);
        }
    });
    
    // Remove injected scripts that contain MCP code
    let scriptCount = 0;
    const scripts = document.querySelectorAll('script');
    scripts.forEach(script => {
        if (script.innerHTML && 
            (script.innerHTML.includes('MCPManagement') || 
             script.innerHTML.includes('mcp-models'))) {
            script.remove();
            scriptCount++;
            console.log('✅ Removed MCP script');
        }
    });
    
    // Clear any MCP-related event listeners (best effort)
    try {
        const buttons = document.querySelectorAll('button');
        buttons.forEach(button => {
            if (button.textContent && button.textContent.includes('MCP')) {
                button.remove();
                console.log('✅ Removed MCP button');
            }
        });
    } catch (e) {
        console.log('ℹ️ Could not clear all event listeners (non-critical)');
    }
    
    console.log('');
    console.log('🎉 MCP Cleanup Complete!');
    console.log(`📊 Removed ${removedCount} DOM elements and ${scriptCount} scripts`);
    console.log('🔄 Consider refreshing the page for a completely clean state');
    console.log('');
    
    // Verification
    const remaining = document.querySelectorAll('[id*="mcp"], [class*="mcp"]');
    if (remaining.length === 0) {
        console.log('✅ Verification: No MCP elements remaining');
    } else {
        console.warn(`⚠️ Warning: ${remaining.length} MCP elements may still exist`);
        remaining.forEach(el => console.log('  Remaining:', el));
    }
})();
EOF
        
        echo "✅ Cleanup script generated: $CLEANUP_SCRIPT"
        echo ""
        echo "USAGE:"
        echo "1. Navigate to https://emailpilot.ai"
        echo "2. Open browser console (F12)"
        echo "3. Copy and paste the contents of: $CLEANUP_SCRIPT"
        echo "4. Press Enter"
        echo ""
        log "Generated cleanup script at $CLEANUP_SCRIPT"
        ;;
        
    3)
        echo ""
        echo "📋 MANUAL REMOVAL INSTRUCTIONS"
        echo "=============================="
        echo ""
        echo "If you're experiencing issues with MCP Management, follow these steps:"
        echo ""
        echo "IMMEDIATE REMOVAL:"
        echo "1. Right-click on the '🤖 MCP Management' button"
        echo "2. Select 'Inspect Element'"
        echo "3. Find the parent div with id='mcp-root'"
        echo "4. Right-click the div and select 'Delete Element'"
        echo ""
        echo "COMPLETE CLEANUP:"
        echo "1. Open browser console (F12)"
        echo "2. Type: document.getElementById('mcp-root')?.remove()"
        echo "3. Type: delete window.MCPManagement"
        echo "4. Type: delete window.MCP_ENDPOINTS"
        echo "5. Refresh the page"
        echo ""
        echo "BROWSER RESET:"
        echo "1. Clear browser cache for emailpilot.ai"
        echo "2. Hard refresh with Ctrl+Shift+R (or Cmd+Shift+R)"
        echo "3. If issues persist, try incognito/private mode"
        echo ""
        echo "TROUBLESHOOTING COMMON ISSUES:"
        echo "• Button won't disappear: Use DOM inspector to manually delete"
        echo "• Console errors: Check if React is loaded on the page"
        echo "• Performance issues: Clear browser cache and refresh"
        echo "• Cloud Function errors: Check network tab in dev tools"
        echo ""
        log "Provided manual removal instructions"
        ;;
        
    *)
        echo "❌ Invalid option. Please run the script again and choose 1, 2, or 3."
        exit 1
        ;;
esac

echo ""
echo "ADDITIONAL HELP:"
echo "==============="
echo "• If MCP was working before: Try running the deployment script again"
echo "• If you see console errors: Check the browser network tab for failed requests"
echo "• If button appears but modal won't open: Check if React is loaded"
echo "• For persistent issues: Clear all browser data for emailpilot.ai"
echo ""
echo "📧 If you need further assistance:"
echo "   Check the TROUBLESHOOTING.md file in the deployment package"
echo ""

log "Rollback process completed successfully"
echo "📝 Rollback log saved to: $LOG_FILE"